### ISSUE TITLE
Create column names via snakecase pkg

### ISSUE THREAD

**Issue by Tazinho** [cutterkom/destatiscleanr#1]
Hi @Cutterkom and thx for this pkg. I was just skimming over your readme and recognizing the issue about dynamically creating column names. Not sure what’s exactly the issue, but if u want a consistent case you could use my snakecase pkg. Just an idea...hope it can help.

**Comment by cutterkom** [comment]
Hi @Tazinho! Thanks for the tipp. Unfortunately, the dynamic column names issue is not about cases, but the dynamic extraction of multi-line headers, depending on the number of rows, see line 37 to 57 in `clean_header.R`
