### ISSUE TITLE
Error: Only strings can be converted to symbols

### ISSUE THREAD

**Issue by gusicadnan** [cutterkom/destatiscleanr#2]
Hello,
When I try to clean that CSV (see attached) which I pulled from Destatis Genesis-Online platform I am getting error:

**Error: Only strings can be converted to symbols**
![error](https://user-images.githubusercontent.com/46894321/51599375-b2fe1300-1eff-11e9-96aa-4961157b39a5.png)

Can you please help me to solve this error, because I am not so good with R?

And btw. this package is very useful and a BIG RESPECT for your work.

Thanks in advance and best regards,

[46241-0001.zip](https://github.com/cutterkom/destatiscleanr/files/2786668/46241-0001.zip)

**Comment by cutterkom** [comment]
hi! thanks for reporting the bug. I know, why it happens. I will push the fixed code tomorrow.

**Comment by cutterkom** [comment]
hi! I fixed the bug. After updating/re-installing the package, you should be able to clean this specific file.

**Comment by gusicadnan** [comment]
Thank you very much. You were super fast :) 
I will test some tables and give you a feedback.

**Comment by gusicadnan** [comment]
I tried about cca. 15 tables today and each has passed without problems. Thank you again!

**Comment by cutterkom** [comment]
great, thanks for testing!
